ifndef::imagesdir[:imagesdir: ../../../imgs/]
ifndef::atomicclassdir[:atomicclassdir: ../../../../../examples/java/src/main/java/kovteba/concurrency]
ifndef::atomicclasstestdir[:atomicclasstestdir: ../../../../examples/java/src/test/java/kovteba/concurrency]


[#java-concurrency-atomic]
=== Атомарні класи
Для виконання атомарних операцій пакет `java.util.concurrent.atomic` має спеціальні класи. Атомарна операція це така операція яку можна безпечно виконати при парлельному виконанні в декількох потоках без блокування або сінхронізаціє.

Прикладом не атомарних операцій є `i++` та `++i` хоч вони і виглядають компактно ало с точки зору JVM не є атомарними, JVM виконує наступні операції:

* читає поточне значення;
* виконує інкрімент або декрімент;
* запис отриманого значення.

Саме тому ці, на перший погляд, прості операції потребують або сінхронізації або блокування. Але сінхронізація або блокування для таких простих операцій занадто дорогі та важкі. Блокування пов'язано з операціоною системою і є небезпека зупинкі і подальшої неможловості продовжити виконання потоку. Або небезпека взаємоблокування. Також додаткові расходи на перемикання потоків.

Блокування має на увазі (песімістичний підхід) дозволяя тільки одному потоку виконувати код. Але є (оптімістичний підхід) коли під час виконання поток виявляє що значення буду змінено іншим потоком то він повторює операцію вже з новим значенням. Цей принцип закладено у атомарні класи.

Модіфікатор `volatile` гарантує виконання відношення <<java-concurrency-happens-before,happens-before>>. Атомарні класи мають метод compareAndSet який і є механізмом оптімістичного блокування дозволяючий змінити змінну тільки як що нове значення дорівнює очікуваному значенню. Якщо значення було змінено іншим потоком то відповідно нове значення не буде дорівнювати ічікуваному і compareAndSet поверне false.

Атомарнимі класами є:

- AtomicBoolean
- AtomicInteger
- AtomicLong
- AtomicReference

Ці класи мають compareAndSet якbй приймає два аргументи передбачуване поточне та нове значення. Якщо ці значення співпадають то цей метод поверне `true` і встановить нове значення якщо метод поверне `false` значення не буде встановлене. Також ці класи має метод getAndSet який безумовно встановляю нове значення і повертає старе. Також маються методи інкрімента да дікрімента.

Також є атомарні класи для масивів де елементи можуть бути змінені атомарно:

- AtomicIntegerArray
- AtomicLongArray
- AtomicReferenceArray

Також є атомарні класи які дозволяють змінювати поля за допомогою рефлексії:

- AtomicIntegerFieldUpdater
- AtomicLongFieldUpdater
- AtomicReferenceFieldUpdater

// TODO
- AtomicStampedReference
- AtomicMarkableReference

ThreadLocal змінні, які є унікальними для кожного потоку. Завдяки цьому можна досягти безпеки використання змінної між потоками наприклад для затраних операцій.

[source,java]
----
include::{atomicclassdir}/threadlocal/ThreadLocalExample1.java[tags=ThreadLocalExample1]
----

Атомарні дії це дії які виконується повністтю або не виконуються зовсім. Жодних ефектів від атомарної дії не видно зовні доти, доки дія не завершиться.
