ifndef::sourcedir[:subdir-java: ../main/java/kovteba]
ifndef::testdir[:testdir: ../../../../test/java]

[#java-concurrency]
== Concurrency

[#java-concurrency-thread-synchronization]
.Сінхронізація
Сінхронізація відноситься до багатопоточності. Сінхронізований блок може бути викликан тільки одним потоком одночасно.

Java підтримує багатопоточність. Це може призвести до того що два чи більше потоків мають доступ до одного теж самого поля чи об'єкту при цьому ймовірні помилки типу втручання в потік *Thread Interference* (приклад можна знайти <<java-concurrency-synchronized-keyword,тут>>), та помилки консистентності пам'яті *Memory Consistency Error*.

Синхронизація це процес який дозволяє виконувати паралельні потоки синхронно. Сінхронізація дозволяє запобігти проблемі узгодженості даних яка трапляється через непослідовний доступ до загальної пам'яті. Якщо метод зазначений як сінхронізований, то поток утримає монітор об'екту під час виконання. Якщо метод вже виконується одним потоком, то новий поток заблокується до того як монітор буде вільний. Досягається завдяки слову `synchronized`. Використовується для методів та блоків коду. Змінні чи атрибути класу не можуть бути позначені цім словом. Синхронізація може призвести до конкуренції потоків <<java-thread-contention,Thread Contention*>>, <<java-concurrency-starvation,Потокове голодування>> та <<java-concurrency-live-lock,Live Lock>> це форми конкуренції потоків.


=== Понятие синхронизация потоков
Синхронизация относится к многопоточности. Синхронизированный блок кода может быть выполнен только одним потоком одновременно.

Java поддерживает несколько потоков для выполнения. Это может привести к тому, что два или более потока получат доступ к одному и тому же полю или объекту. Синхронизация — это процесс, который позволяет выполнять все параллельные потоки в программе синхронно. Синхронизация позволяет избежать ошибок согласованности памяти, вызванных непоследовательным доступом к общей памяти. Когда метод объявлен как синхронизированный — нить держит монитор для объекта, метод которого исполняется. Если другой поток выполняет синхронизированный метод, ваш поток заблокируется до тех пор, пока другой поток не отпустит монитор. Синхронизация достигается в Java использованием зарезервированного слова `synchronized`. Вы можете использовать его в своих классах определяя синхронизированные методы или блоки. Вы не сможете использовать `synchronized` в переменных или атрибутах в определении класса.









