ifndef::mdddir[:mdddir: ../../../examples/java/src/main/java/kovteba/concurrency]
ifndef::mddimgsdir[:mddimgsdir: ../../imgs]
ifndef::mddtestdir[:mddtestdir: ../../../examples/java/src/test/java/kovteba/concurrency]

ifndef::imagesdir[:imagesdir: ../imgs]

//Methodology

[#event-storming]
=== Event Storming
[[event-storming-definition]]*Event Storming* - як сказав Альберто Брандоліні, це колаборативний процес, який допомагає розкрити знання про доменну модель, використовуючи інтенсивну комунікацію між учасниками(між представниками бізнесу, експертамі в домені та розробниками) і дозволяє витратит на це "години, а не дні або тижні". Процес який зміщує акцет з технічної складової на бізнес складову. Дуже гарно підхдить до модулювання мікросервісів.

Event storing має свою грамитику яки поліпшує розуміння та фіксувати знання про домен та упорядковувати історію замість набору абстракцій.

Є головні концепції Event Storming:

- *Domain event* - це основна концепція Event Storming з світу експертів в предметній області. Формулюється як дієслово в минулому часі, виглядає як помаранчевий квадрат.
- *Hotspot*(Незадоволеність) - це конфліктні області, які можуть виникати під час обговорення. Вони можуть бути вирішені або відкладені на майбутнє. Виглядають як малинові квадрати.
- *Timeline* - це ось часу, яка вказує порядок подій. Виглядає як лінія.
- *Chaotic exploration* - це фаза, яка використовується на початку проведення Event Storming. Учасники, кожен самостійно, розміщають всі події, які приходять їм в голову в тому порядку, в якому, на їхню думку, ці події відбуваються.
- *Enforce the timeline* - це фаза, яка використовується після хаотичного дослідження, в рамках якої всі події упорядковуються на єдиній вісі часу і усуваються дублікати подій.

Існують три основні рівні досліджень Event Storming:

1. *Big Picture* - це великомасштабне дослідження.
2. *Process Modeling* - це моделювання процесу.
3. *Software Design* - це проектування програмного забезпечення.

.Big Picture
На рівні Big Picture ми дивимся на картину в цілому, наприклад при запуске нивих продуктів, ретроспективи вивчення огранізації. На цьому рівні ми додаємо декілька нових концепцій:

- *Opportunity* (Возможность) – протилежність незадоволеності (hotspot), це є якась вигода або можливість. Відображається зеленим квадратом.
- *Actor* (Действующее лицо) - людина або група людей(команда, департамент тощо) на яких і які можут вплавати на Domin Event. Видображається жовтим квадратом.
- *System* (Система) - система яка використовуєтсья для вирішенні доменної проблеми. Відображається рожевим прямокутником.
- *Value* (Ценность) - це може показувати де в домені цінність. Відображається зеленим або червоним стікером які позначають місця які знижать або підвищують цінність.
- *Pivotal Events* (Поворотные события) - найважливіші події для бізнеса та зазвичай в який зацікавленно найбільша кількість людей.
- *Swimlanes* (Параллельные потоки)- паралельні потоки подій які відбуваються в один час, або для різних Actor.

.Process Modeling
Process Modeling - це моделювання процесів, які відбуваються в організації. Цей рівень Event Storming відповідає за моделювання бізнес-процесів та сервісів. На цьому єтапі ми досліджуємо окремий процесс. На цьому рівні ми також додаємо декілька нових концепцій:

* Command (Команда) - дія або рішення які може бути ініційоване actor або якимось автоматичним процесом. Відображається голобим квадратом.
* Policy (Правило)- реакія на якусь дію (якщо трапилось А то робимо Б). Може бути як реацією Actor або автоматичне. Відображається бузковим прямокутником.
* Read Model (информация, Модель чтения) - інформація на базі якої приймається рішення. Модель читання визначається експертами в предметній області. Відображається зеленим квадратом.

Процес починаєть зі збору подій які є в бізнесі які будують у хронологичному пордку також додають команди яки викликають подію та актори які викликають події. Завдяки токій граматиці можливо сформувати загальну мову між розробкою та бізнесом. В ідеальному сценарію ми отримаємо модель яка є відображенням реально предметної області і максимально приближено до реальності

.Software Design
Software Design - це проектування програмного забезпечення. На цьому єтапі ми додаємо технічні реалізації до бізнес процесів. Як результат повинні отримати схему рішення від якої вже переходять до дізайну. Також додає нову концепцію:

* Aaggregate* (Агрегат) - термін з <<domain-driven-design,DDD>> група пов'язаних сущностей які розглядаються як едине ціле. Що можна розглядати у термінах <<domain-driven-design,DDD>> як <<domain-driven-design-bounded-context,bounded context>>. Відображається жовтим квадратом.

.Example
//TODO

Як заключення можна сказати що як що треба описати Event Storming одним словом то це буде "дослідження" яке спочатку схоже на хаос який по трохи здобуває урегултовану форму.

// sources
// https://agilemindset.ru/%D1%87%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-event-storming/
// https://habr.com/ru/companies/oleg-bunin/articles/537862/
// https://habr.com/ru/companies/runity/articles/689620/
