ifndef::mdddir[:mdddir: ../../../examples/java/src/main/java/kovteba/concurrency]
ifndef::mddimgsdir[:mddimgsdir: ../../imgs]
ifndef::mddtestdir[:mddtestdir: ../../../examples/java/src/test/java/kovteba/concurrency]

[#model-driven-design]
=== MDD (Model Driven Design)
[[model-driven-development-definition]]*MDD (Model Driven Design)* - це методологія розробки програмного забезпечення, яка базується на використанні моделей для опису системи та генерації коду з цих моделей. MDD дозволяє підвищити продуктивність розробки, оскільки дозволяє автоматизувати процеси розробки та підтримки програмного забезпечення. Крім того, використання MDD дозволяє покращити якість програмного забезпечення, оскільки дозволяє покращити розуміння системи та зменшити кількість помилок в коді.


Основные идеи
Для конструирования программного приложения должна быть построена подробная, формально точная модель, из которой потом может быть автоматически генерирован исполняемый программный код приложения.

Основные шаги разработки:

* Сначала разрабатывается модель предметной области проектируемого приложения, полностью независимая от имплементирующей технологии. Она называется Platform Independent Model (PIM).
* Затем PIM автоматически трансформируется специальным инструментом в платформо-зависимую модель (Platform Specifical Model, PSM).
* PSM переводится в исходный код на соответствующем языке программирования.
Такова схема в идеальном OMG-мире. В реальных современных проектах часть бизнес-логики приходится реализовать вручную. Но поскольку этот код отделен от генерированного системой, большой проблемы это не представляет.[1]

Примеры
Примером реализации MDA можно считать технологию CASEBERRY и платформу Flexberry, разрабатываемую с её помощью.
В основе разработки лежит UML-модель, создаваемая при помощи собственного инструмента создания UML-диаграмм. Есть возможность генерации как Windows, так и Web-приложений на языке C#. Генерируемый код делится на 2 части: первую часть генератор кода будет перезаписывать при внесении изменений в модель, вторая часть останется для него неприкасаемой. Таким образом, можно наращивать функциональность создаваемого приложения параллельно с внесением изменений в модель, при этом функциональность не будет утеряна при перегенерации кода.
Бизнес-логика вынесена в отдельный проект, для её реализации создаются заготовки, значительно облегчающие её (бизнес-логики) добавление.

