ifndef::imagesdir[:imagesdir: ../../imgs]

[#functional-programming]
=== Functional Programming
*Функціональне програмування (Functional Programming або FP) — це парадигма програмування, яка ставить функції в центр уваги. У FP ми намагаємося писати код, який є більш декларативним, менш залежним від стану та побічних ефектів.*

Ось 5 «китів», на яких тримається ФП:

1. <<functional-programming-pure-functions,Чисті функції (Pure Functions)>>;
2. <<Незмінність (Immutability)>>;
3. <<Функції як об'єкти першого класу (First-Class Citizens)>>;
4. <<Функції вищого порядку (Higher-Order Functions)>>;
5. <<Декларативність>>.


[#functional-programming-pure-functions]
.Чисті функції (Pure Functions)

Функція вважається чистою, якщо вона відповідає двом умовам:

* Детермінованість: Для однакових вхідних даних результат завжди однаковий;
* Відсутність побічних ефектів (Side Effects): Функція не змінює нічого зовні (не пише в базу, не змінює глобальні змінні, не виводить у консоль). Вона просто обчислює результат.

Відсутність побічних ефектів (No Side Effects). Це означає: «Функція  не повинна нічого змінювати в навколишньому середовищі. Що вважається побічним ефектом:

* Зміна глобальної змінної;
* Модифікація списку або об'єкта, який передали як аргумент;
* Запис у файл або базу даних;
* print() у консоль.

[#functional-programming-immutability]
.Незмінність (Immutability)
У ФП ви не можете змінити значення змінної після того, як вона була створена. Замість того, щоб змінити елемент у списку, ви створюєте новий список із новими даними. Це автоматично розв'язує проблеми багатопоточності (Concurrency/Thread Safety), оскільки потоки не можуть змінити стан об'єктів одночасно. Також це робить код більш передбачуваним і легким для відлагодження. Ти можеш передати об'єкт у будь-яку функцію і бути впевненим, що вона не змінить його "під капотом". Твій код стає легшим для читання і відлагодження. Також завдяки незмінності ми маємо історію станів (Time Travel Debugging). Оскільки в тебе зберігаються старі копії даних, ти легко можеш "відкотитися" до предыдущего состояния программы.

Яле з'являється логічне питання "Як же працювати з великими даними, якщо ми постійно все копіюємо?" Ти можеш запитати: "Якщо я буду копіювати список з мільйоном елементів кожного разу, пам'ять просто закінчиться!". На щастя, що під капотом функціональні мови (і бібліотеки Python, такі як Pyrsistent) використовують Persistent Data Structures. Замість повного копіювання вони створюють "дерево", де стара і нова версії даних ділять спільні частини. Змінюється лише маленька гілка.

[#functional-programming-first-class-citizens]
.Функції як об'єкти першого класу (First-Class Citizens). Це означає, що з функціями можна поводитися так само як зі змінними:

* Передавати їх як аргументи в інші функції;
* Повертати їх з функцій;
* Зберігати їх у структурах даних.

Що це нам дає:

* Функцию можно присвоить переменной. Вы можете дать функции «псевдоним».

[source,python]
----
def say_hello(name):
    return "Hello, {name}!"

greeting = say_hello # Присваиваем функцию переменной (без скобок!)
print(greeting("Ivan")) # Вызываем через переменную
----

* Функцию можно хранить в структурах данных. Это часто используют для замены громоздких if-elif-else (паттерн Strategy).

[source,python]
----
def fast_fix(data): return data.strip()
def heavy_fix(data): return data.replace("_", " ").upper()

# Список функций-обработчиков
pipeline = [fast_fix, heavy_fix]

text = "  some_bad_data  "
for function in pipeline:
text = function(text)

print(text) # "SOME BAD DATA"
----

[#functional-programming-higher-order-functions]
.Функції вищого порядку (Higher-Order Functions)
Це функції, які приймають інші функції як параметри або повертають їх. Найвідоміші приклади, які ти бачив у Java Streams: map(), filter(), reduce().


[#functional-programming-declarative]
.Декларативність
Ти кажеш коду: «Відфільтруй мені всі активні підписки», а не пишеш цикл for, створюєш тимчасовий список і вручну перекладаєш туди елементи.

[#functional-programming-closures]
.Замикання (Closures) — магия ФП. Оскільки функції — це об'єкти, ми можемо створювати функції всередині інших функцій і повертати їх. При цьому внутрішня функція «запам'ятовує» оточення, в якому вона була створена. Тобто це функція яка таще за собою змінні з того місця, де вона була створена. Це дуже потужний інструмент, який дозволяє створювати функції з «пам'яттю» про своє оточення.

Три умови для замыкания:

1. Є вкладена функція (функція всередині функції);
2. Внутрішня функція використовує переменную из внешней (родительской) функции;
3. Зовнішня функція возвращает внутреннюю функцию.


Пример «в лоб»
Представь, что у нас есть функция, которая создает «приветствия».

[source,python]
----
def simple_closure(greeting_text):
# Это внешняя переменная greeting_text

    def say_hello(name):
        # Внутренняя функция "видит" greeting_text
        return f"{greeting_text}, {name}!"

    return say_hello # Возвращаем саму функцию, НЕ вызывая её

# Создаем конкретное замыкание
morning_greet = simple_closure("Good morning")
evening_greet = simple_closure("Good evening")

print(morning_greet("Ivan")) # "Good morning, Ivan!"
print(evening_greet("Ivan")) # "Good evening, Ivan!"
----

Тобто функція simple_closure вже давно завершила свою роботу, її змінні повинні були видалитися з пам'яті. Але morning_greet все ще пам'ятає, що greeting_text був "Good morning". Вона «замкнула» в себе эту змінну.







