ifndef::imagesdir[:imagesdir: ../../../../../../imgs/]
ifndef::setdir[:setdir: ../../../../../../../../examples/java/src/main/java/kovteba/collectionframework/iterable/collection/set]
ifndef::settestdir[:settestdir: ../../../../../../../../examples/java/src/main/java/kovteba/collectionframework/iterable/collection/set]

[#java-collection-framework-set]
===== Set
`Set` - який дозволяє зберігати тільки унікальні елементи. Це означає, що в `Set` не може бути дублікатів. Якщо ви спробуєте додати дублікат в `Set`, він просто проігнорується.

// [source,subs="normal"]
// ----
└──  [I] <<java-collection-framework-set,Set<E>>>
    ├── [I] <<java-collection-framework-sorted-set,SortedSet<E>>>
    │   └── [I] <<java-collection-framework-navigableset,NavigableSet<E>>>
    │       └── [A] AbstractSet<E>
    │           ├── [C] <<java-collection-framework-treeset,TreeSet<E>>>
    │           └── [CC] ConcurrentSkipListSet<E>
    │
    └── [A] AbstractSet<E>
        ├── [C] <<java-collection-framework-hash-set,HashSet<E>>>
        │   └── [C] <<java-collection-framework-linkedhashset,LinkedHashSet<E>>>
        ├── [A] EnumSet<E>
        │   ├── [C] RegularEnumSet<E>
        │   └── [C] JumboEnumSet<E>
        └── [CC] CopyOnWriteArraySet<E>
// ----

[#java-collection-framework-set-interface-methods]
.`Set` інтерфейс має наступні методи:
- `boolean add(E e)` - додає елемент в `Set`, якщо він не був там раніше;
- `boolean remove(Object o)` - видаляє елемент з `Set`, якщо він там є;
- `int size()` - повертає кількість елементів в `Set`;
- `void clear()` - видаляє всі елементи з `Set`;
- `boolean contains(Object o)` - повертає `true`, якщо `Set` містить вказаний елемент;
- `boolean isEmpty()` - повертає `true`, якщо `Set` не містить жодного елемента;
- `Iterator<E> iterator()` - повертає ітератор для `Set`.


include::hashset/collection-framework-hash-set-class.adoc[]
include::sortedset/collection-framework-interface-sorted-set.adoc[]








//TODO 15. В чем отличия TreeSet и HashSet?

Начнем с того, что Set — это множество (так же называют «набором»). Set не допускает хранение двух одинаковых элементов. Формально говоря, термин «множество» и так обозначает совокупность различных элементов, очень важно, что именно различных элементов, так как это главное свойство Set. С учетом такого определения, пояснение про хранение одинаковых элементом не требуется, но в обиходе, понятие «множество» потеряло свой строгий смысл касательно уникальности элементов, входящих в него, поэтому все же уточняйте отдельно данное свойство множества.

TreeSet обеспечивает упорядоченно хранение элементов в виде красно-черного дерева. Сложность выполнения основных операций в TreeSet lg N. HashSet использует для хранения элементов такой же подход, что и HashMap, за тем отличием, что в HashSet в качестве ключа выступает сам элемент, кроме того HashSet (как и HashMap) не поддерживает упорядоченное хранение элементов и обеспечивает временную сложность выполнения операций аналогично HashMap.

// TODO 16. Устройство TreeSet?

Этот вопрос задают вместо вопроса 14 и здесь достаточно краткого ответа, что TreeSet основан на красно-черном дереве. Как правило этого хватает и собеседник сразу переходит к следующему вопросу, у меня ни разу не спрашивали механизм балансировки дерева или другие подробности его реализации.

Для экспресс углубления знаний по красно-черному дереву рекомендую вот эту статью.


// TODO 17. Что будет, если добавлять элементы в TreeSet по возрастанию?

Обычно данный вопрос собеседник предваряет фразой, что в основе TreeSet лежит бинарное дерево и если добавлять элементы по возрастанию, то как они будут распределены по дереву.

Если нет точного представления об устройстве TreeSet, а есть общее понимание о том, что это бинарное дерево (в чем нас дополнительно уверяет собеседник), то данный вопрос может привести к интересному результату: все элементы после доабвления в обычное бинарное дерево будут находится в одной ветви длиной N элементов, что сводит на нет, все преимущества такой структуры, как дерево (фактически получается список). На самом, деле, как выше упоминалось в основе TreeSet лежит красно-черное дерево, которое умеет само себя балансировать. В итоге, TreeSet все равно в каком порядке вы добавляете в него элементы, преимущества этой структуры данных будут сохраняться.
