[#questions]
== QUESTIONS

[#architecture]
.Architecture

[#architecture-cap-theory]
- Що буде, якщо Consul втратить 2 вузли в кластері з 5? Які гарантії збережуться? <<cap-theorem-quorum,Answer>>

[#service-discovery-questions]
.Service Discovery Questions
- Що таке Service Discovery і чому він важливий у розподілених системах? <<service-discovery-definition,Answer>>
- Які основні типи Service Discovery ви знаєте? Поясніть різницю між ними. <<service-discovery-types,Answer>>
- Що таке Client-side discovery? <<client-side-discovery,Answer>>
- Як працює Client-side discovery? <<client-side-discovery-how-it-works,Answer>>
- Які переваги та недоліки Client-side discovery? <<client-side-discovery-pros-and-cons,Answer>>
- Що таке Server-side discovery? <<server-side-discovery,Answer>>
- Як працює Server-side discovery? <<server-side-discovery-how-it-works,Answer>>
- Які переваги та недоліки Server-side discovery? <<server-side-discovery-pros-and-cons,Answer>>
- Що таке DNS-based discovery? <<dns-based-discovery,Answer>>
- Як працює DNS-based discovery? <<dns-based-discovery-how-it-works,Answer>>
- Які переваги та недоліки DNS-based discovery? <<dns-based-discovery-pros-and-cons,Answer>>
- Що таке Key-Value Store-based discovery? <<key-value-store-based-discovery,Answer>>
- Як працює Key-Value Store-based discovery? <<key-value-store-based-discovery-how-it-works,Answer>>
- Які переваги та недоліки Key-Value Store-based discovery? <<key-value-store-based-discovery-pros-and-cons,Answer>>
- Які переваги та недоліки кожного типу Service Discovery? <<service-discovery-types-comparison,Answer>>
- Де використовується Service Discovery? <<service-discovery-where-used,Answer>>
- Що дає Service Discovery у контексті мікросервісної архітектури? <<service-discovery-what-for,Answer>>
- Які інструменти для Service Discovery ви знаєте? <<service-discovery-tools,Answer>>
- Які головні компоненти системи Service Discovery? <<service-discovery-main-components,Answer>>

[#architecture-uml-diagrams]
.UML Diagrams
- Що таке UML? <<uml-definition,Answer>>
- Які основні типи діаграм UML? <<uml-diagram-types,Answer>>
- Які діаграми відносяться до Поведенкових діаграм? <<uml-diagram-behavioral-diagram-types,Answer>>
- Які діаграми відносяться до Структурних діаграм? <<uml-diagram-structural-diagram-types,Answer>>
- Які найпопулярніші типи діаграм UML? <<uml-diagram-most-popular-types,Answer>>
- Наведіть порівняльну таблицю типів діаграм UML. <<uml-diagram-comparative-table,Answer>>
- Яка послідовність використання діаграм UML? <<uml-diagram-usage-sequence,Answer>>

.Activity Diagram
- Що таке UML Activity Diagram?<<uml-activity-diagram-definition,Answer>>
- Які головні цілі UML Activity Diagram?<<uml-activity-diagram-main-goals,Answer>>
- Які головні елементи UML Activity Diagram?<<uml-activity-diagram-main-elements,Answer>>
- Наведіть приклад UML Activity Diagram.<<uml-activity-diagram-example,Answer>>

.Communication Diagram
- Що таке UML Communication Diagram?<<uml-communication-diagram-definition,Answer>>

.Interaction Overview Diagram
- Що таке UML Interaction Overview Diagram?<<uml-interaction-overview-diagram-definition,Answer>>

.Sequence Diagram
- Що таке UML Sequence Diagram?<<uml-sequence-diagram,Answer>>
- Які головні цілі UML Sequence Diagram?<<uml-sequence-diagram-main-goals,Answer>>
- Які основні елементи UML Sequence Diagram?<<uml-sequence-diagram-main-elements,Answer>>

.State Machine Diagram
- Що таке UML State Machine Diagram?<<uml-state-machine-diagram-definition,Answer>>
- Які головні цілі UML State Machine Diagram?<<uml-state-machine-diagram-main-goals,Answer>>
- Які головні елементи UML State Machine Diagram?<<uml-state-machine-diagram-main-elements,Answer>>

- Що таке Package Diagram? <<uml-package-diagram-definition,Answer>>
- Що таке UML Deployment Diagram?<<uml-deployment-diagram-definition>>
- Які головні цілі UML Deployment Diagram?<<uml-deployment-diagram-main-goals>>
- Які головні елементи UML Deployment Diagram?<<uml-deployment-diagram-main-elements>>
- Наведіть приклад UML Deployment Diagram.<<uml-deployment-diagram-example>>
- Що таке UML Use Case Diagram?<<uml-use-case-diagram-definition,Answer>>
- Які головні цілі UML Use Case Diagram?<<uml-use-case-diagram-main-goals,Answer>>
- Які головні елементи UML Use Case Diagram?<<uml-use-case-diagram-main-elements,Answer>>
- Наведіть приклад UML Use Case Diagram.<<uml-use-case-diagram-example,Answer>>


[#devops]
.DevOps
[#devops-docker]
.Docker

[#devops-docker-image]
.Docker Image
- Що таке Docker Image? <<docker-image-definition,Answer>>
- Яку структуру має Docker Image? <<docker-image-structure,Answer>>
- З чого складається Docker Image? <<docker-image-layers,Answer>>
- Що таке Layer в Docker Image? <<docker-layer,Answer>>
- Що таке Layer Cache в Docker Image? <<docker-layer-cache,Answer>>
- Які типи Docker Image існують? <<docker-image-types,Answer>>
- Як зберігати секрети в Docker Image? <<docker-secret,Answer>>
- Як створити Docker Image? <<docker-image-creation,Answer>>
- Як створити Docker Image з Multi-stage build? <<docker-multi-stage-build,Answer>>
- Як завантажити Docker Image з реєстру? <<docker-image-pulling,Answer>>
- Як опублікувати Docker Image в реєстр? <<docker-image-pushing,Answer>>
- Як додати теги до Docker Image? <<docker-image-tagging,Answer>>
- Як перевірити інформацію про Docker Image? <<docker-image-inspection,Answer>>
- Як видалити Docker Image? <<docker-image-remove,Answer>>

[#devops-docker-dockerfile]
.Dockerfile
- Що таке Dockerfile? <<docker-dockerfile-definition,Answer>>
- Головні інструкції які використовуються в Dockerfile? <<docker-dockerfile-instructions,Answer>>
- Що означає `FROM` в Dockerfile? <<docker-dockerfile-from-definition,Answer>>
- Використання `FROM`. <<docker-dockerfile-from-usage,Answer>>
- Best Practices для `FROM`. <<docker-dockerfile-from-best-practices,Answer>>
- Що означає `RUN` в Dockerfile? <<docker-dockerfile-run-definition,Answer>>
- Використання `RUN`. <<docker-dockerfile-run-usage,Answer>>
- Best Practices для `RUN`. <<docker-dockerfile-run-best-practices,Answer>>
- Що означає `CMD` в Dockerfile? <<docker-dockerfile-cmd-definition,Answer>>
- Використання `CMD`. <<docker-dockerfile-cmd-usage,Answer>>
- Кратко про `CMD`. <<docker-dockerfile-cmd-summary,Answer>>
//TODO - Best Practices для `CMD`. <<docker-dockerfile-cmd-best-practices,Answer>>
- Що означає `ENTRYPOINT` в Dockerfile? <<docker-dockerfile-entrypoint-definition,Answer>>
- Використання `ENTRYPOINT`. <<docker-dockerfile-entrypoint-usage,Answer>>
- Кратко про `ENTRYPOINT`. <<docker-dockerfile-entrypoint-summary,Answer>>
//TODO - Best Practices для `ENTRYPOINT`. <<docker-dockerfile-entrypoint-best-practices,Answer>>
- В чому різниця між `CMD` та `ENTRYPOINT`. <<docker-dockerfile-cmd-vs-entrypoint,Answer>>
- Що означає `COPY` в Dockerfile? <<docker-dockerfile-copy-definition,Answer>>
- Що означає `ADD` в Dockerfile? <<docker-dockerfile-add-definition,Answer>>
- Використання `ADD`. <<docker-dockerfile-add-usage,Answer>>
- В чому різниця між `COPY` та `ADD`. <<docker-dockerfile-copy-vs-add,Answer>>
- Що означає `WORKDIR` в Dockerfile? <<docker-dockerfile-workdir-definition,Answer>>
- Що означає `EXPOSE` в Dockerfile? <<docker-dockerfile-expose-definition,Answer>>
- Що означає `ENV` в Dockerfile? <<docker-dockerfile-env-definition,Answer>>
- Використання `ENV`. <<docker-dockerfile-env-usage,Answer>>
- Що означає `ARG` в Dockerfile? <<docker-dockerfile-arg-definition,Answer>>
- Використання `ARG`. <<docker-dockerfile-arg-usage,Answer>>
- В чому різниця між `ENV` та `ARG`. <<docker-dockerfile-arg-vs-env,Answer>>
- Best Practices для `ENV` та `ARG`. <<docker-dockerfile-arg-vs-env-best-practices,Answer>>
- Коротко для `ENV` та `ARG`. <<docker-dockerfile-arg-vs-env-summary,Answer>>
- Що означає `USER` в Dockerfile? <<docker-dockerfile-user-definition,Answer>>
- Що означає `VOLUME` в Dockerfile? <<docker-dockerfile-volume-definition,Answer>>
- Що означає `LABEL` в Dockerfile? <<docker-dockerfile-label-definition,Answer>>
- Що означає `HEALTHCHECK` в Dockerfile? <<docker-dockerfile-healthcheck-definition,Answer>>
- Що означає `SHELL` в Dockerfile? <<docker-dockerfile-shell-definition,Answer>>
- Як тестувати Dockerfile? <<docker-dockerfile-testing, Answer>>
- Best Practices при роботі з Dockerfile? <<docker-dockerfile-best-practices, Answer>>

[#devops-docker-volume]
.Docker Volume
- Що таке VOLUME в Docker? <<docker-volumes-definition,Answer>>
- Чи можна підключати один том до декількох контейнерів? <<docker-volume-share-between-containers,Answer>>
- Які типи томів існують в Docker? <<docker-volumes-types,Answer>>
- Що таке Anonymous Volume? <<docker-volume-anonymous-volume,Answer>>
- Що таке Bind Mount? <<docker-volume-bind-mount,Answer>>
- Що таке Named Volume? <<docker-volume-named-volume,Answer>>
- Різниця між Bind Mount та Volume? <<docker-bind-nount-vs-volume,Answer>>
- Різниця між Named Volume та Bind Mount <<docker-volume-name-vs-path,Answer>>
- Різниця між Named Volume та Bind Mount та Anonymous Volume? <<docker-bind-nount-vs-volume-vs-named,Answer>>
- Необхідно лі монтувати volume для запису логів додатку? <<docker-application-log-volume,Answer>>
- Цілі використання томів в Docker? <<docker-volumes-usage,Answer>>
- Які драйвери доступні для томів в Docker? <<docker-volume-drivers,Answer>>
- Опції для під час створення Volume? <<docker-volume-options,Answer>>
- Як видалити невикорсовуємі тома? <<docker-volume-prune,Answer>>
- Як подивитись все доступні Volumes? <<docker-volume-get-all-volumes,Answer>>

[#devops-docker-container]
.Docker Container
- Що таке Docker Container? <<docker-container-definition,Answer>>
- Відмінності Docker Container від VM? <<docker-container-vs-vm, Answer>>
- Чому Docker Container запускається швидше, ніж VM? <<docker-container-vs-vm, Answer>>
- Как запустить контейнер в фоновом режиме? <<docker-container-run-flags-detach,Answer>>
- Як обмежити ресурси контейнера по CPU та пам'яті?<<docker-container-limit-resources, Answer>>
- Які стани може мати контейнер? <<docker-container-state,Answer>>
- Через що контейнер може бути завершеним одразу після запуску? <<docker-container-end-immediately,Answer>>
- Чим відрізняються `docker stop` від `docker kill`? <<docker-container-kill-vs-stop,Answer>>
- Флаги `docker run`? <<docker-container-run-flags, Answer>>
- Як зменьшити час запуску Spring Boot в контейнере? <<docker-container-start-speed-up,Answer>>
- Як шукати проблеми мережі між контейнерами? <<docker-container-network-problem,Answer>>
- Як і які обмеження можно задати і якими фалгами? <<docker-container-resource-limit-flags,Answer>>
- Як виконати команду в середені запущеного контейнеру? <<docker-container-run-command-inside,Answer>>
- Як подивитись логі працюючого контейнера? <<docker-container-logs,Answer>>
- Як зробити порт видиммин наружу контейнера? <<docker-container-publish-flag,Answer>>
- Як встановити змінні середовища при запуске контейнера? <<docker-container-env-flag,Answer>>
- Чи можна використовувати файл зі змінними для запуску контейнера? <<docker-container-env-file-flag,Answer>>
- Як обмежити доступ до контейнеру зовні? <<docker-container-outside-limit-access, Answer>>
- Як передати файли до контейнеру (або навпаки) без пересборки образу? <<docker-container-file-trasfer,Answer>>
- Як зберегти данні при перезапуску контейнера? <<docker-container-save-data-beetwen-restart,Answer>>
- Як додати Capabilities є у контейнера? <<docker-container-add-capabilities,Answer>>
- Як перевірити, які Capabilities є у контейнера? <<docker-container-check-capabilities,Answer>>
- Що робить флаг `--privileged` при запуску контейнера? <<docker-container-privileged-flag,Answer>>
- Навіщо використовувати non-root user всередині Docker-контейнера? <<docker-container-non-root-user,Answer>>
- Як запустити контейнер без сетевого стека? <<docker-container-run-without-network,Answer>>
- Як забеспечується безпека Docker-контейнерів? <<docker-container-security,Answer>>
- Головні аспекти безпеки Docker-контейнерів? <<docker-container-security-summary,Answer>>
- Яким чином Docker Container забезпечує ізоляцію процесів? <<docker-container-process-isolation,Answer>>
- Які Best Practices Docker-контейнерів? <<docker-container-best-practices,Answer>>
//- Как задать параметры JVM в контейнере? <<docker-container-jvm-args, Answer>>
//- Почему Java-приложение внутри контейнера может видеть неправильное время или таймзону? <<docker-container-incorrect-timezone, Answer>>
//- Как проверить, что контейнер с Java-приложением корректно «живой»? (Healthcheck) <<docker-container-healthcheck, Answer>>
//- Как подгрузить внешние конфигурационные файлы (application.yml) в контейнер? <<docker-container-config-files, Answer>>
//- Что такое Testcontainers в Java? <<docker-testcontainer-for-java, Answer>>