ifndef::streamtestdir[:streamtestdir: ../../../../../examples/java/src/test/java/kovteba/stream]

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest1]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest1Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest1Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest2]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest2Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest2Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest3]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest3Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest3Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest4]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest4Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest4Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest5]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest5Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest5Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest6]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest6Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest6Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest7]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest7Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest7Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest8]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest8Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest8Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest9]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest9Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest9Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest10]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest10Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest10Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest12]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest12Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest12Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest14]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest14Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest14Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest15]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest15Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest15Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest16]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest16Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest16Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest17]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest17Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest17Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest18]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest18Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest18Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest20]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest20Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest20Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest21]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest21Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest21Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest22]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest22Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest22Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest25]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest25Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest25Answer]
====

.Який результат виконання коду?
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest26]
----
[source,java]
----
include::{streamtestdir}/StreamTest.java[tags=streamTest26Variants]
----

.Answer
[%collapsible]
====
include::{streamtestdir}/StreamTest.java[tags=streamTest26Answer]
====
