ifndef::imagesdir[:imagesdir: ../../../imgs/]
ifndef::streamtestdir[:streamtestdir: ../../../../../examples/spring/src/test/java/kovteba/stream]

[#spring-aop]
=== AOP
AOP (Aspect-Oriented Programming) — це парадигма програмування, яка базується на ідеї розділення функціональності для покращення розбиття програми на модулі. AOP і Spring - взаємодоповнюючі технології, які дозволяють вирішувати складні проблеми шляхом розділення функціоналу на окремі модулі. AOP надає можливість реалізації наскрізної логіки - тобто логіки, яка застосовується до багатьох частин програми - в одному місці і забезпечення автоматичного застосування цієї логіки по всій програмі. Підхід Spring до AOP полягає у створенні "динамічних проксі" для цільових об'єктів і "прив'язуванні" об'єктів до конфігурованому раді для виконання наскрізної логіки.

Головні концепції AOP:

* Аспект (англ. aspect) - модуль або клас, який реалізує наскрізну функціональність. Аспект змінює поведінку іншого коду, застосовуючи раді в точках з'єднання, визначених деяким зрізом.
* Рада (англ. advice) - фрагмент коду, який повинен виконуватися в окремій точці з'єднання. Існує кілька типів рад, рада може бути виконаний до, після або замість точки з'єднання.
* Точка з'єднання (англ. joinpoint) - це чітко визначена точка в виконуваній програмі, де слід застосувати раду. Типові приклади точок з'єднання включають звернення до методу, власне Method Invocation, ініціалізацію класу і створення екземпляра об'єкта. Багато реалізації AOP дозволяють використовувати виклики методів і звернення до полів об'єкта в якості точок з'єднання.
* Зріз (англ. pointcut) - набір точок з'єднання. Зріз визначає, чи підходить дана точка з'єднання до даної ради. Найзручніші реалізації AOP використовують для визначення зрізів синтаксис основної мови (наприклад, в AspectJ застосовуються Java-сигнатури) і дозволяють їх повторне використання за допомогою перейменування і комбінування.
* Прив'язування(англ. weaving) представляє собою процес дійсної вставки аспектів в певну точку коду програми. Для рішень AOP часу компіляції це робиться на етапі компіляції, зазвичай у вигляді додаткового кроку процесу збірки. Аналогічно, для рішень AOP часу виконання прив'язування відбувається динамічно під час виконання. В AspectJ підтримується ще один механізм прив'язування під назвою прив'язування під час завантаження (load-time weaving - LTW), який перехоплює лежачий в основі завантажувач класів JVM і забезпечує прив'язування з байт-кодом, коли він завантажується завантажувачем класів;
* Ціль (англ. target) - це об'єкт, потік виконання якого змінюється якимось процесом AOP. На цільовий об'єкт часто посилаються як на об'єкт, оснащений радою;
* Впровадження (англ. introduction, введення) - являє собою процес, за допомогою якого можна змінити структуру об'єкта за рахунок введення в нього додаткових методів або полів, зміна ієрархії наслідування для додавання функціональності аспекту в чужий код. Зазвичай реалізується за допомогою деякого метаоб'єктного протоколу (англ. metaobject protocol, MOP).

Типи AOP:

* Статичний AOP - процес прив'язування відбувається під час компіляції або завантаження класу;
* Динамічний AOP - процес прив'язування відбувається динамічно під час виконання.

.Різниця між Spring AOP і AspectJ АОП
AspectJ і Spring AOP є двома популярними реалізаціями AOP в екосистемі Java.

- Spring AOP немного проще, т.к. нет необходимости следить за процессом связывания.
- Spring AOP поддерживает аннотации AspectJ, таким образом мы можем работать в спринг проекте похожим образом с AspectJ проектом.
- Spring AOP поддерживает только proxy-based АОП и может использовать только один тип точек соединения - Method Invocation. AspectJ поддерживает все виды точек соединения.
- Недостатком Spring AOP является работа только со своими бинами, которые существуют в Spring Context.
